
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfijjitkzifscjrxzxli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1maWpqaXRremlmc2Nqcnh6eGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTM3MTMsImV4cCI6MjA1OTE2OTcxM30.VH5339eBnWlQAEbpVwK6ND0NA-VMj8a0043dv6F5-cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions to manually type the table operations since the generated types might not be up to date
export type Tables = {
  participants: {
    Row: {
      id: string;
      name: string;
      email: string;
      phone?: string;
      organization?: string;
      photo?: string;
      registration_date?: string;
      scanned?: boolean;
      approved?: boolean;
      type?: string;
      media?: string;
      formula?: string;
    };
    Insert: {
      id?: string;
      name: string;
      email: string;
      phone?: string;
      organization?: string;
      photo?: string;
      registration_date?: string;
      scanned?: boolean;
      approved?: boolean;
      type?: string;
      media?: string;
      formula?: string;
    };
    Update: {
      id?: string;
      name?: string;
      email?: string;
      phone?: string;
      organization?: string;
      photo?: string;
      registration_date?: string;
      scanned?: boolean;
      approved?: boolean;
      type?: string;
      media?: string;
      formula?: string;
    };
  };
  admin_profiles: {
    Row: {
      id: string;
      name: string;
      email: string;
      role: string;
      last_login?: string;
    };
    Insert: {
      id: string;
      name: string;
      email: string;
      role?: string;
      last_login?: string;
    };
    Update: {
      id?: string;
      name?: string;
      email?: string;
      role?: string;
      last_login?: string;
    };
  };
};

// Type-safe query helpers
export function from<T extends keyof Tables>(
  table: T
) {
  return supabase.from(table);
}
